import * as THREE from "three";
import {OrbitControls} from "three/addons/controls/OrbitControls.js";
import {ROOT,clip,edit,moveObject,rotateObject,dropObject,setTransform,placementStatus,objectBounds,worldBoxes,normalizeObject,makeFacePattern,scaleCopiedPattern,validate,copyCell,pasteCell,fillRegion,eraseRegion,recolorRegion,cellFromCoordinates,adjacentCell,hasDetailedOccupancy,validatePatterns} from "./space.mjs";

const $=s=>document.querySelector(s);
const colors=["#ff5349","#ff7a2f","#f5a623","#f5d547","#a8db4b","#48b85b","#1ba784","#16a6a1","#35bce3","#4a9df1","#4263d8","#5c52c9","#8756d9","#ae54cf","#dd4eab","#f06292","#9f304d","#a74435","#82563a","#c79b63","#ead9a5","#91d4b1","#b5e2e8","#b8ccec","#c3b5e7","#f1f2ed","#b7bdc7","#7f8793","#535c68","#343941","#17191e","#c46f44"];
const KEY="block32-spatial-v3",OLD_KEY="block32-spatial-v2",PATTERN_KEY="block32-patterns-v1";
const blankObject=(name="Room structure",kind="fixed")=>({id:crypto.randomUUID(),name,kind,transform:{position:kind==="movable"?[0,1000,0]:[0,0,0],rotation:[0,0,0]},boxes:[]});
let world={version:3,unit:"mm",room:{size:[10000,10000,10000]},objects:[blankObject()]};
let owner=world.objects[0].id,workspace="arrange",path=[],selected=null,tool="select",color=colors[0],layer=0,classified=false,protectDetail=true,preventCollisions=true,patterns=[],clipboard=null;
let down=null,multi=false,noticeTimer;
const object=()=>world.objects.find(o=>o.id===owner);
const region=()=>path.at(-1)||ROOT;
const step=()=>(region().max[0]-region().min[0])/10;
const length=v=>v>=1000?(v/1000)+" m":v>=10?(v/10)+" cm":v+" mm";
const run=fn=>{try{fn();}catch(e){say(e.message);}};
function say(message){$("#toast").textContent=message;$("#toast").classList.add("visible");clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$("#toast").classList.remove("visible"),4500);}
function mode(next){tool=next;$("#place-tool").classList.toggle("active",next==="place");$("#erase-tool").classList.toggle("active",next==="erase");$("#place-tool").setAttribute("aria-pressed",next==="place");$("#erase-tool").setAttribute("aria-pressed",next==="erase");$("#select-tool").setAttribute("aria-pressed",next==="select");$("#mode-badge").textContent=(workspace==="arrange"?"OBJECT":next.toUpperCase())+" MODE";$("#mode-badge").dataset.mode=workspace==="arrange"?"object":next;}
function save(){try{localStorage.setItem(KEY,JSON.stringify(world));$("#save-state").textContent="Saved locally";}catch{$("#save-state").textContent="Export JSON to save";say("Browser storage unavailable. Save JSON to keep your work.");}refresh();}
function confirmDetailedChange(cell,verb){return !protectDetail||!hasDetailedOccupancy(object().boxes,cell)||confirm(verb+" this cell will replace finer modeling inside it. Continue?");}
function updateGeometry(fn){object().boxes=fn(object().boxes);save();}

const workspacePanel=document.createElement("section");workspacePanel.className="panel-section workspace-panel";
workspacePanel.innerHTML='<div class="section-label">Workspace</div><div class="segmented workspace-switch"><button id="arrange-mode" class="segment active" type="button">Arrange room</button><button id="edit-mode" class="segment" type="button">Edit object</button></div><p class="storage-note workspace-note">Select and position complete objects in continuous room space.</p>';
$(".tool-panel").prepend(workspacePanel);

const navigation=document.createElement("section");navigation.className="panel-section navigation edit-only";
navigation.innerHTML='<div id="scale"></div><div id="crumbs"></div><p id="selection">Select a cell to inspect its contents.</p><button id="select-tool" class="button">Select cell</button> <button id="enter" class="button">Enter cell</button><label>Editing layer <input id="layer" type="range" min="0" max="9" value="0"><span id="layer-value">0</span></label><div class="cell-picker"><label>X <input id="cell-x" type="number" min="0" max="9" value="0"></label><label>Y <input id="cell-y" type="number" min="0" max="9" value="0"></label><label>Z <input id="cell-z" type="number" min="0" max="9" value="0"></label><button id="pick-cell" class="button">Select coordinates</button></div><label class="detail-protection"><input id="protect-detail" type="checkbox" checked> Warn before replacing detailed contents</label><div class="adjacent-panel"><div class="adjacent-heading">Select adjacent cell</div><div class="adjacent-actions"><button class="button" data-axis="0" data-delta="-1">X− Left</button><button class="button" data-axis="0" data-delta="1">X+ Right</button><button class="button" data-axis="1" data-delta="-1">Y− Down</button><button class="button" data-axis="1" data-delta="1">Y+ Up</button><button class="button" data-axis="2" data-delta="-1">Z− Back</button><button class="button" data-axis="2" data-delta="1">Z+ Front</button></div></div>';
workspacePanel.after(navigation);

const bulk=document.createElement("section");bulk.className="panel-section bulk-panel edit-only";
bulk.innerHTML='<div class="section-label">Repeat & fill</div><button id="copy-cell" class="button">Copy cell</button><fieldset class="paste-destination"><legend>Paste destination · cell 0–9</legend><div class="cell-picker">'+["x","y","z"].map(a=>'<label>'+a.toUpperCase()+'<input id="paste-'+a+'" type="number" min="0" max="9" step="1" value="0"></label>').join("")+'</div><p id="paste-preview" class="storage-note">Copy a cell, then choose its destination.</p><button id="paste-cell" class="button">Paste cell here</button></fieldset><p id="clipboard-status" class="storage-note">Copied geometry stays local to the active object.</p><details><summary>Rectangular fill or erase</summary><div class="fill-fields">'+[["x","Width (X)","1"],["y","Height (Y)","0.03"],["z","Depth (Z)","1"]].map(([id,label,value])=>'<label>'+label+'<input id="fill-'+id+'" type="number" min="0.001" max="10" step="0.001" value="'+value+'"></label>').join("")+'</div><label>Units <select id="fill-unit"><option value="1000">Meters</option><option value="10">Centimeters</option><option value="1">Millimeters</option></select></label><p id="fill-origin" class="storage-note"></p><div class="rectangle-actions"><button id="fill-region" class="button">Fill rectangle</button><button id="erase-region" class="button rectangle-erase">Erase rectangle</button></div></details>';
navigation.after(bulk);

const patternsPanel=document.createElement("section");patternsPanel.className="panel-section pattern-panel edit-only";
patternsPanel.innerHTML='<div class="section-label">Patterns</div><label>Pattern <select id="pattern-select"></select></label><div class="pattern-thickness"><label>Thickness <input id="pattern-thickness" type="number" min="0.1" step="0.1" value="1" inputmode="decimal"></label><label>Units <select id="pattern-thickness-unit"><option value="1">Millimeters</option><option value="10">Centimeters</option><option value="percent">% of cell</option></select></label></div><p id="pattern-preview" class="pattern-preview" aria-live="polite"></p><div class="pattern-actions"><button id="apply-pattern" class="button">Replace selected cell</button><button id="save-pattern" class="button">Save selected cell</button><button id="delete-pattern" class="text-button danger">Delete saved pattern</button></div><p class="storage-note">Replace removes the selected cell first, then inserts the pattern. Built-ins use the exact thickness and current color shown above; saved patterns keep their own colors and scale proportionally.</p>';
bulk.after(patternsPanel);

const objects=document.createElement("section");objects.className="panel-section object-panel";
objects.innerHTML='<div class="section-label">Object</div><label>Active object <select id="objects"></select></label><label>Name <input id="object-name" maxlength="100"></label><label>Type <select id="kind"><option value="fixed">Structure · locked</option><option value="movable">Movable</option></select></label><div class="object-actions"><button id="new-object" class="button">New</button><button id="duplicate-object" class="button">Duplicate</button><button id="delete-object" class="text-button danger">Delete</button></div><div class="arrange-only transform-panel"><div class="section-label">Room position · cm</div><div class="transform-fields">'+["x","y","z"].map((a,i)=>'<label>'+a.toUpperCase()+'<input id="pos-'+a+'" type="number" step="0.1" inputmode="decimal"></label>').join("")+'</div><label>Move step <select id="move-step"><option value="1000">1 meter</option><option value="100">10 centimeters</option><option value="10" selected>1 centimeter</option><option value="1">1 millimeter</option></select></label><label class="collision-lock"><input id="prevent-collisions" type="checkbox" checked> Stop at walls and other objects</label><div id="movement" class="movement-grid"></div><div class="section-label rotation-label">Rotate 90°</div><div id="rotation" class="movement-grid"></div><button id="drop-object" class="button drop-button">Drop to surface</button><p id="placement-status" class="placement-status"></p></div><label><input id="classification" type="checkbox"> Show types: structure gray / movable blue</label><p id="dimensions"></p><p class="storage-note edit-only">You are editing only the local geometry of this object.</p><p class="storage-note arrange-only">Position is independent of the room grid. Geometry moves and rotates as one rigid object.</p>';
$(".tool-panel").insertBefore(objects,$(".tool-section"));
$(".tool-section").classList.add("edit-only");$(".palette-section").classList.add("edit-only");$(".world-section").classList.add("edit-only");
$("#clear-button").textContent="Clear active object";
$("#viewport-hint").textContent="Select an object · Drag to orbit · Scroll to zoom";
$("#selected-color-name").textContent=color;

const customColor=document.createElement("div");customColor.className="custom-color";
customColor.innerHTML='<label for="custom-color-picker">Custom color</label><input id="custom-color-picker" type="color" value="#ff5349"><input id="custom-color-hex" type="text" value="#ff5349" maxlength="7" spellcheck="false">';
$("#palette").after(customColor);
const recolorButton=document.createElement("button");recolorButton.id="recolor-cell";recolorButton.className="button recolor-button edit-only";recolorButton.textContent="Apply color to selected cell";customColor.after(recolorButton);
const modeBadge=document.createElement("div");modeBadge.id="mode-badge";modeBadge.setAttribute("aria-live","polite");$(".viewport-wrap").append(modeBadge);
const viewShortcuts=document.createElement("div");viewShortcuts.className="view-shortcuts";viewShortcuts.innerHTML='<button data-view="front">Front</button><button data-view="back">Back</button><button data-view="left">Left</button><button data-view="right">Right</button><button data-view="top">Top</button><button data-view="bottom">Bottom</button>';$(".viewport-wrap").append(viewShortcuts);

const scene=new THREE.Scene();scene.background=new THREE.Color("#0d0f13");
const camera=new THREE.PerspectiveCamera(42,1,.01,150);const renderer=new THREE.WebGLRenderer({canvas:$("#viewport"),antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));
const controls=new OrbitControls(camera,$("#viewport"));controls.enableDamping=true;controls.minDistance=2;controls.maxDistance=40;controls.maxPolarAngle=Math.PI;
scene.add(new THREE.HemisphereLight(0xffffff,0x59616e,2.5));const light=new THREE.DirectionalLight(0xffffff,2);light.position.set(4,12,8);scene.add(light);
const grid=new THREE.GridHelper(10,10,0xd6e7ff,0x71849b);grid.material.transparent=true;grid.material.opacity=.78;scene.add(grid);
const latticePoints=[];for(let a=0;a<=10;a++)for(let b=0;b<=10;b++){latticePoints.push(-5,a,b-5,5,a,b-5,a-5,0,b-5,a-5,10,b-5,a-5,b,-5,a-5,b,5);}
const latticeGeometry=new THREE.BufferGeometry();latticeGeometry.setAttribute("position",new THREE.Float32BufferAttribute(latticePoints,3));
const lattice=new THREE.LineSegments(latticeGeometry,new THREE.LineBasicMaterial({color:0x7890aa,transparent:true,opacity:.24,depthWrite:false}));lattice.renderOrder=2;scene.add(lattice);
const floor=new THREE.Mesh(new THREE.PlaneGeometry(10,10),new THREE.MeshBasicMaterial({visible:false,side:THREE.DoubleSide}));floor.rotation.x=-Math.PI/2;scene.add(floor);
const bounds=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.BoxGeometry(10,10,10)),new THREE.LineBasicMaterial({color:0x657486,transparent:true,opacity:.45}));bounds.position.y=5;scene.add(bounds);
const highlight=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.BoxGeometry(1,1,1)),new THREE.LineBasicMaterial({color:0xffe16a,depthTest:false}));highlight.visible=false;highlight.renderOrder=10;scene.add(highlight);
const geometry=new THREE.BoxGeometry(1,1,1),group=new THREE.Group();scene.add(group);const ray=new THREE.Raycaster(),pointer=new THREE.Vector2(),matrix=new THREE.Matrix4();let meshes=[];
function home(){camera.up.set(0,1,0);camera.position.set(13,12,15);controls.target.set(0,4,0);controls.update();}
function standardView(name){camera.up.set(0,1,0);controls.target.set(0,5,0);if(name==="front")camera.position.set(0,5,18);if(name==="back")camera.position.set(0,5,-18);if(name==="right")camera.position.set(18,5,0);if(name==="left")camera.position.set(-18,5,0);if(name==="top"){camera.up.set(0,0,-1);camera.position.set(0,21,.001);}if(name==="bottom"){camera.up.set(0,0,1);camera.position.set(0,-11,.001);}controls.update();}
viewShortcuts.querySelectorAll("button").forEach(b=>b.onclick=()=>standardView(b.dataset.view));
function local(v,i){return (v-region().min[i])/step()-(i===1?0:5);}
function addBatch(id,c,boxes,roomSpace){const m=new THREE.InstancedMesh(geometry,new THREE.MeshLambertMaterial({color:c}),boxes.length);boxes.forEach((b,i)=>{const center=b.min.map((v,j)=>(v+b.max[j])/2),size=b.min.map((v,j)=>b.max[j]-v);const pos=roomSpace?new THREE.Vector3(center[0]/1000-5,center[1]/1000,center[2]/1000-5):new THREE.Vector3(...center.map((v,j)=>local(v,j)));const scale=roomSpace?new THREE.Vector3(...size.map(v=>v/1000)):new THREE.Vector3(...size.map(v=>v/step()));matrix.compose(pos,new THREE.Quaternion(),scale);m.setMatrixAt(i,matrix);});m.userData.objectId=id;group.add(m);meshes.push(m);}

function refresh(){
  for(const m of meshes){group.remove(m);m.material.dispose();m.dispose();}meshes=[];
  const ob=object();if(!ob)return;
  if(workspace==="arrange"){
    const batches=new Map();
    for(const o of world.objects)for(const b of worldBoxes(o)){const c=classified?(o.kind==="fixed"?"#a4abb5":"#4a9df1"):b.color,key=o.id+"|"+c;if(!batches.has(key))batches.set(key,{id:o.id,c,boxes:[]});batches.get(key).boxes.push(b);}
    for(const batch of batches.values())addBatch(batch.id,batch.c,batch.boxes,true);
    lattice.visible=false;grid.position.y=.001;floor.position.y=0;highlight.visible=false;
    const b=objectBounds(ob,"world");if(b){highlight.visible=true;highlight.position.set((b.min[0]+b.max[0])/2000-5,(b.min[1]+b.max[1])/2000,(b.min[2]+b.max[2])/2000-5);highlight.scale.set(...b.min.map((v,i)=>(b.max[i]-v)/1000));}
  }else{
    const batches=new Map();for(const box of ob.boxes){const b=clip(box,region());if(!b)continue;const c=classified?(ob.kind==="fixed"?"#a4abb5":"#4a9df1"):b.color;if(!batches.has(c))batches.set(c,[]);batches.get(c).push(b);}for(const [c,boxes] of batches)addBatch(ob.id,c,boxes,false);
    lattice.visible=true;grid.position.y=layer+.001;floor.position.y=layer;highlight.visible=!!selected;if(selected){highlight.position.set(...selected.min.map((v,i)=>local(v+step()/2,i)));highlight.scale.set(1,1,1);}
  }
  document.body.dataset.workspace=workspace;$("#arrange-mode").classList.toggle("active",workspace==="arrange");$("#edit-mode").classList.toggle("active",workspace==="edit");$(".workspace-note").textContent=workspace==="arrange"?"Select and position complete objects in continuous room space.":"Build the active object in its own local 10 m workspace.";
  $("#viewport-hint").textContent=workspace==="arrange"?"Select an object · Drag to orbit · Scroll to zoom":"Click to edit local geometry · Drag to orbit · Scroll to zoom";
  $("#objects").replaceChildren(...world.objects.map(o=>{const opt=new Option(o.name,o.id);opt.selected=o.id===owner;return opt;}));$("#object-name").value=ob.name;$("#kind").value=ob.kind;
  const b=objectBounds(ob);$("#dimensions").textContent=b?"Object size: "+[0,1,2].map(i=>length(b.max[i]-b.min[i])).join(" × "):"No geometry yet.";
  ["x","y","z"].forEach((a,i)=>{$("#pos-"+a).value=(ob.transform.position[i]/10).toFixed(1).replace(/\.0$/,"");$("#pos-"+a).disabled=ob.kind!=="movable";});
  const status=placementStatus(world,owner);$("#placement-status").textContent="Placement: "+status.reason;$("#placement-status").classList.toggle("invalid",!status.valid);
  const locked=ob.kind!=="movable"||!ob.boxes.length;$("#movement").querySelectorAll("button").forEach(b=>b.disabled=locked);$("#rotation").querySelectorAll("button").forEach(b=>b.disabled=locked);$("#drop-object").disabled=locked;
  $("#delete-object").disabled=world.objects.length===1;$("#duplicate-object").disabled=!ob.boxes.length;
  if(workspace==="edit"){
    $("#scale").textContent="Local cell: "+length(step())+" · View: "+length(step()*10)+" cube";$("#layer-value").textContent=layer+" · "+length(layer*step())+" above local origin";
    $("#crumbs").replaceChildren();for(let d=0;d<=path.length;d++){const button=document.createElement("button");button.className="text-button";button.textContent=d===0?ob.name:length(10000/10**d)+" cell";button.onclick=()=>{path=path.slice(0,d);selected=null;layer=0;$("#layer").value=0;mode("select");refresh();home();};$("#crumbs").append(button);}
    $("#enter").disabled=!selected||step()<=1;$("#copy-cell").disabled=!selected;$("#paste-cell").disabled=!selected||!clipboard||clipboard.size[0]!==step();$("#fill-region").disabled=!selected;$("#erase-region").disabled=!selected;$("#recolor-cell").disabled=!selected;$("#apply-pattern").disabled=!selected;
    navigation.querySelectorAll(".adjacent-actions button").forEach(button=>{try{if(!selected)throw Error();adjacentCell(selected,Number(button.dataset.axis),Number(button.dataset.delta),region());button.disabled=false;}catch{button.disabled=true;}});
    $("#fill-origin").textContent=selected?"Local start: "+selected.min.map(length).join(" / "):"Select a starting cell.";$("#selection").textContent=selected?"Local cell origin: "+selected.min.map(length).join(" / "):"Select a cell to inspect its contents.";
    if(selected){const xyz=selected.min.map((v,i)=>Math.round((v-region().min[i])/step()));["x","y","z"].forEach((a,i)=>$("#paste-"+a).value=xyz[i]);$("#paste-preview").textContent="Yellow outline: cell "+xyz.join(" / ");}updatePatternPreview();
  }
  $("#cube-count").textContent=world.objects.length+" "+(world.objects.length===1?"object":"objects")+" · "+world.objects.reduce((n,o)=>n+o.boxes.length,0)+" regions";mode(tool);
}

function setWorkspace(next){if(workspace==="edit"&&next==="arrange")normalizeObject(world,owner);workspace=next;selected=null;path=[];layer=0;$("#layer").value=0;mode("select");save();home();}
$("#arrange-mode").onclick=()=>setWorkspace("arrange");$("#edit-mode").onclick=()=>setWorkspace("edit");
$("#select-tool").onclick=()=>mode("select");$("#place-tool").onclick=()=>mode("place");$("#erase-tool").onclick=()=>mode("erase");
$("#objects").onchange=e=>{owner=e.target.value;selected=null;path=[];refresh();};
$("#object-name").onchange=e=>{object().name=e.target.value.trim()||"Untitled object";save();};
$("#kind").onchange=e=>{object().kind=e.target.value;save();};
$("#new-object").onclick=()=>{if(world.objects.length>=1000)return say("Object limit reached.");const o=blankObject("Object "+(world.objects.length+1),"movable");world.objects.push(o);owner=o.id;save();setWorkspace("edit");$("#object-name").focus();$("#object-name").select();};
$("#duplicate-object").onclick=()=>run(()=>{const source=object();normalizeObject(world,source.id);const copy=structuredClone(source),bounds=objectBounds(source,"world"),gap=100,w=bounds.max[0]-bounds.min[0]+gap,h=bounds.max[1]-bounds.min[1]+gap,d=bounds.max[2]-bounds.min[2]+gap;copy.id=crypto.randomUUID();copy.name=(source.name+" copy").slice(0,100);copy.kind="movable";world.objects.push(copy);owner=copy.id;let placed=false;for(const delta of [[w,0,0],[-w,0,0],[0,0,d],[0,0,-d],[0,h,0]]){try{setTransform(world,copy.id,{position:source.transform.position.map((v,i)=>v+delta[i]),rotation:[...source.transform.rotation]});placed=true;break;}catch{}}if(!placed){world.objects.pop();owner=source.id;throw Error("No clear nearby position for a duplicate.");}save();});
$("#delete-object").onclick=()=>{if(world.objects.length>1&&confirm("Delete this object and all of its geometry?")){world.objects=world.objects.filter(o=>o.id!==owner);owner=world.objects[0].id;selected=null;path=[];save();}};
$("#classification").onchange=e=>{classified=e.target.checked;refresh();};
$("#prevent-collisions").onchange=e=>{preventCollisions=e.target.checked;say(preventCollisions?"Collision blocking on.":"Collision blocking off. Objects can pass through walls while arranging.");};
for(let i=0;i<3;i++)for(const sign of [-1,1]){const b=document.createElement("button");b.className="button";b.textContent=["X","Y","Z"][i]+(sign<0?" −":" +");b.onclick=()=>run(()=>{normalizeObject(world,owner);const d=[0,0,0];d[i]=sign*Number($("#move-step").value);moveObject(world,owner,d,{allowCollision:!preventCollisions});save();});$("#movement").append(b);const r=b.cloneNode(true);r.onclick=()=>run(()=>{normalizeObject(world,owner);rotateObject(world,owner,i,sign*90,{allowCollision:!preventCollisions});save();});$("#rotation").append(r);}
$("#drop-object").onclick=()=>run(()=>{dropObject(world,owner);save();});
for(const a of ["x","y","z"])$("#pos-"+a).onchange=()=>run(()=>{if(object().kind!=="movable")throw Error("Fixed structures are locked. Change the type first.");normalizeObject(world,owner);const position=["x","y","z"].map(k=>Math.round(Number($("#pos-"+k).value)*10));if(position.some(v=>!Number.isFinite(v)))throw Error("Enter valid centimeter positions.");setTransform(world,owner,{position,rotation:[...object().transform.rotation]},{allowCollision:!preventCollisions});save();});

function chooseColor(next,swatch){if(!/^#[0-9a-f]{6}$/i.test(next))throw Error("Enter a six-digit color such as #2f80ed.");color=next.toLowerCase();$("#selected-color-name").textContent=color;$("#custom-color-picker").value=color;$("#custom-color-hex").value=color;$("#palette").querySelectorAll("button").forEach(s=>{s.classList.toggle("selected",s===swatch);s.setAttribute("aria-selected",s===swatch);});updatePatternPreview();}
colors.forEach(c=>{const b=document.createElement("button");b.type="button";b.className="swatch";b.style.setProperty("--swatch",c);b.setAttribute("aria-label",c);b.setAttribute("role","option");b.onclick=()=>chooseColor(c,b);$("#palette").append(b);});
$("#custom-color-picker").oninput=e=>chooseColor(e.target.value,null);$("#custom-color-hex").onchange=e=>run(()=>chooseColor(e.target.value.trim(),null));
recolorButton.onclick=()=>run(()=>{if(!selected)throw Error("Select a cell first.");updateGeometry(boxes=>recolorRegion(boxes,selected,color));mode("select");});

$("#pick-cell").onclick=()=>run(()=>{selected=cellFromCoordinates(region(),["#cell-x","#cell-y","#cell-z"].map(s=>Number($(s).value)));layer=Math.round((selected.min[1]-region().min[1])/step());$("#layer").value=layer;mode("select");refresh();});
navigation.querySelectorAll(".adjacent-actions button").forEach(button=>button.onclick=()=>run(()=>{if(!selected)throw Error("Select a cell first.");selected=adjacentCell(selected,Number(button.dataset.axis),Number(button.dataset.delta),region());layer=Math.round((selected.min[1]-region().min[1])/step());$("#layer").value=layer;mode("select");refresh();}));
$("#enter").onclick=()=>{if(!selected||step()<=1)return;path.push(selected);selected=null;layer=0;$("#layer").value=0;mode("select");refresh();home();};$("#layer").oninput=e=>{layer=Number(e.target.value);refresh();};
function backToParent(){if(workspace!=="edit"||!path.length)return;selected=path.pop();layer=Math.round((selected.min[1]-region().min[1])/step());$("#layer").value=layer;mode("select");refresh();home();}
window.addEventListener("keydown",e=>{if(e.key==="Escape"&&!e.target.closest?.("input,select,textarea,[contenteditable]")){e.preventDefault();backToParent();}});
$("#protect-detail").onchange=e=>{protectDetail=e.target.checked;};

$("#copy-cell").onclick=()=>run(()=>{if(!selected)throw Error("Select a cell first.");clipboard=copyCell(object().boxes,selected);mode("select");refresh();say("Cell copied.");});
function previewPaste(){run(()=>{selected=cellFromCoordinates(region(),["x","y","z"].map(a=>Number($("#paste-"+a).value)));layer=Number($("#paste-y").value);$("#layer").value=layer;mode("select");refresh();});}
for(const a of ["x","y","z"])$("#paste-"+a).oninput=previewPaste;
$("#paste-cell").onclick=()=>run(()=>{if(!selected||!clipboard)throw Error("Copy a cell and select a destination first.");if(!confirmDetailedChange(selected,"Paste into"))return;updateGeometry(boxes=>pasteCell(boxes,selected,clipboard));say("Cell pasted.");});
$("#fill-unit").onchange=()=>{const unit=Number($("#fill-unit").value);for(const a of ["x","y","z"]){const el=$("#fill-"+a),old=Number(el.dataset.unit||1000);el.value=String(Number(el.value)*old/unit);el.dataset.unit=String(unit);}};
function rectangle(){if(!selected)throw Error("Select a starting cell first.");const unit=Number($("#fill-unit").value),dims=["x","y","z"].map(a=>{const raw=Number($("#fill-"+a).value)*unit,mm=Math.round(raw);if(!Number.isFinite(raw)||mm<=0||Math.abs(raw-mm)>.000001)throw Error("Use positive dimensions with at least 1 mm precision.");return mm;}),cell={min:[...selected.min],max:selected.min.map((v,i)=>v+dims[i])};return {cell,dims};}
$("#fill-region").onclick=()=>run(()=>{const {cell,dims}=rectangle();if(!confirmDetailedChange(cell,"Fill"))return;updateGeometry(boxes=>fillRegion(boxes,cell,color));say("Rectangle filled: "+dims.map(length).join(" × "));});
$("#erase-region").onclick=()=>run(()=>{const {cell,dims}=rectangle();if(!confirmDetailedChange(cell,"Erase"))return;updateGeometry(boxes=>eraseRegion(boxes,cell));say("Rectangle erased: "+dims.map(length).join(" × "));});

const builtins=[
 ["floor","Face · bottom",["bottom"]],["ceiling","Face · top",["top"]],["left","Face · left",["left"]],["right","Face · right",["right"]],["front","Face · front",["front"]],["back","Face · back",["back"]],
 ["bottom-left","Edge · bottom left",["bottom","left"]],["bottom-right","Edge · bottom right",["bottom","right"]],["bottom-front","Edge · bottom front",["bottom","front"]],["bottom-back","Edge · bottom back",["bottom","back"]],
 ["top-left","Edge · top left",["top","left"]],["top-right","Edge · top right",["top","right"]],["top-front","Edge · top front",["top","front"]],["top-back","Edge · top back",["top","back"]],
 ["left-front","Edge · left front",["left","front"]],["left-back","Edge · left back",["left","back"]],["right-front","Edge · right front",["right","front"]],["right-back","Edge · right back",["right","back"]],
 ["bottom-left-front","Corner · bottom left front",["bottom","left","front"]],["bottom-left-back","Corner · bottom left back",["bottom","left","back"]],["bottom-right-front","Corner · bottom right front",["bottom","right","front"]],["bottom-right-back","Corner · bottom right back",["bottom","right","back"]],
 ["top-left-front","Corner · top left front",["top","left","front"]],["top-left-back","Corner · top left back",["top","left","back"]],["top-right-front","Corner · top right front",["top","right","front"]],["top-right-back","Corner · top right back",["top","right","back"]]
];
function savePatterns(){localStorage.setItem(PATTERN_KEY,JSON.stringify(patterns));renderPatterns();}
function renderPatterns(){const select=$("#pattern-select"),current=select.value;select.replaceChildren(...builtins.map(([id,name])=>new Option(name,"builtin:"+id)),...patterns.map((p,i)=>new Option(p.name,"saved:"+i)));if([...select.options].some(o=>o.value===current))select.value=current;updatePatternPreview();}
function patternThickness(){
 const value=Number($("#pattern-thickness").value),unit=$("#pattern-thickness-unit").value,size=step();
 if(!Number.isFinite(value)||value<=0)throw Error("Enter a positive pattern thickness.");
 const raw=unit==="percent"?size*value/100:value*Number(unit),thickness=Math.round(raw);
 if(Math.abs(raw-thickness)>.000001)throw Error("Pattern thickness must resolve to a whole millimeter.");
 if(thickness<1||thickness>size)throw Error("Thickness must be between 1 mm and "+length(size)+".");
 return thickness;
}
function updatePatternPreview(){const value=$("#pattern-select")?.value||"",item=builtins.find(p=>p[0]===value.slice(8));$("#delete-pattern").hidden=!value.startsWith("saved:");if(!$("#pattern-preview"))return;if(item){try{$("#pattern-preview").innerHTML='<span class="pattern-chip" style="--pattern-color:'+color+'"></span>'+item[1]+' · '+length(patternThickness())+' thick · '+color;}catch(e){$("#pattern-preview").textContent=e.message;}}else{const saved=patterns[Number(value.slice(6))];$("#pattern-preview").textContent=saved?'Saved pattern · stored colors · scaled to '+length(step())+' cell':"Choose a pattern.";}}
$("#pattern-select").onchange=updatePatternPreview;$("#pattern-thickness").oninput=updatePatternPreview;$("#pattern-thickness-unit").onchange=updatePatternPreview;$("#save-pattern").onclick=()=>run(()=>{if(!selected)throw Error("Select a modeled cell first.");const copied=copyCell(object().boxes,selected),name=prompt("Pattern name");if(!name?.trim())return;patterns.push({name:name.trim().slice(0,60),copied});savePatterns();say("Pattern saved.");});
$("#apply-pattern").onclick=()=>run(()=>{if(!selected)throw Error("Select a destination cell first.");const value=$("#pattern-select").value,item=builtins.find(p=>p[0]===value.slice(8));let copied,description;if(value.startsWith("builtin:")){if(!item)throw Error("Choose a pattern first.");const thickness=patternThickness();copied=makeFacePattern(step(),item[2],thickness,color);description=item[1]+" · "+length(thickness)+" · "+color;}else{const saved=patterns[Number(value.slice(6))];if(saved){copied=scaleCopiedPattern(saved.copied,step());description=saved.name+" · scaled to "+length(step());}}if(!copied)throw Error("Choose a pattern first.");if(!confirmDetailedChange(selected,"Using this pattern in"))return;updateGeometry(boxes=>pasteCell(boxes,selected,copied));mode("select");say("Replaced cell with "+description+".");});
$("#delete-pattern").onclick=()=>{const i=Number($("#pattern-select").value.slice(6));if(patterns[i]&&confirm("Delete saved pattern “"+patterns[i].name+"”?")){patterns.splice(i,1);savePatterns();}};

function cellAt(e){const rect=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(meshes,false)[0];let p;if(hit)p=hit.point.clone().addScaledVector(hit.face.normal,tool==="place"?.00001:-.00001);else{const h=ray.intersectObject(floor)[0];if(!h)return null;p=h.point.clone();p.y=layer+.00001;}const xyz=[p.x+5,p.y,p.z+5].map(Math.floor);if(xyz.some(v=>v<0||v>9))return null;const min=xyz.map((v,i)=>region().min[i]+v*step());return {min,max:min.map(v=>v+step())};}
const pointers=new Set();renderer.domElement.addEventListener("pointerdown",e=>{pointers.add(e.pointerId);if(pointers.size>1)multi=true;down={x:e.clientX,y:e.clientY,id:e.pointerId,moved:false};});renderer.domElement.addEventListener("pointermove",e=>{if(down&&Math.hypot(e.clientX-down.x,e.clientY-down.y)>5)down.moved=true;});
renderer.domElement.addEventListener("pointerup",e=>{const click=down&&!down.moved&&!multi&&down.id===e.pointerId&&e.button===0;pointers.delete(e.pointerId);if(!pointers.size)multi=false;down=null;if(!click)return;run(()=>{const rect=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(pointer,camera);if(workspace==="arrange"){const hit=ray.intersectObjects(meshes,false)[0];if(hit?.object.userData.objectId){owner=hit.object.userData.objectId;refresh();}return;}const cell=cellAt(e);if(!cell)return;selected=cell;if(tool==="select"){refresh();return;}if(!confirmDetailedChange(cell,tool==="erase"?"Erase":"Place over")){mode("select");refresh();return;}updateGeometry(boxes=>tool==="erase"?eraseRegion(boxes,cell):edit(boxes,cell,color));});});
renderer.domElement.addEventListener("pointercancel",()=>{pointers.clear();down=null;multi=false;});

$("#load-button").onclick=()=>$("#file-input").click();$("#save-button").onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({...world,patterns},null,2)],{type:"application/json"})),a=document.createElement("a"),d=new Date(),pad=n=>String(n).padStart(2,"0");a.href=url;a.download='block32-objects-'+d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate())+'_'+pad(d.getHours())+'-'+pad(d.getMinutes())+'-'+pad(d.getSeconds())+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$("#file-input").onchange=async e=>{const f=e.target.files[0];e.target.value="";if(!f)return;if(f.size>15000000)return say("Please use a JSON file under 15 MB.");try{const raw=JSON.parse(await f.text()),next=validate(raw),nextPatterns=raw.patterns===undefined?patterns:validatePatterns(raw.patterns);if(world.objects.some(o=>o.boxes.length)&&!confirm("Replace this room with the imported file?"))return;world=next;patterns=nextPatterns;if(!world.objects.length)world.objects.push(blankObject());world.objects.forEach(o=>normalizeObject(world,o.id));owner=world.objects[0].id;savePatterns();setWorkspace("arrange");save();}catch(err){say(err.message);}};
$("#clear-button").onclick=()=>{if(confirm("Clear all geometry from the active object?"))updateGeometry(()=>[]);};$("#reset-view").onclick=home;for(const [id,factor] of [["#zoom-in",.82],["#zoom-out",1.22]])$(id).onclick=()=>{const v=camera.position.clone().sub(controls.target);v.setLength(THREE.MathUtils.clamp(v.length()*factor,2,40));camera.position.copy(controls.target).add(v);controls.update();};

try{const saved=localStorage.getItem(KEY),old=localStorage.getItem(OLD_KEY);if(saved)world=validate(JSON.parse(saved));else if(old){world=validate(JSON.parse(old));localStorage.setItem(KEY,JSON.stringify(world));say("Your existing room was upgraded: every object now has independent local geometry and room placement.");}world.objects.forEach(o=>normalizeObject(world,o.id));localStorage.setItem(KEY,JSON.stringify(world));owner=world.objects[0]?.id||owner;}catch{say("Local save could not be opened. It has been left untouched; import a JSON backup.");}
try{patterns=validatePatterns(JSON.parse(localStorage.getItem(PATTERN_KEY)||"[]"));}catch{patterns=[];}
function resize(){const r=$(".viewport-wrap");renderer.setSize(r.clientWidth,r.clientHeight,false);camera.aspect=r.clientWidth/r.clientHeight;camera.updateProjectionMatrix();}new ResizeObserver(resize).observe($(".viewport-wrap"));
renderPatterns();home();mode("select");refresh();resize();$("#loading-note").remove();renderer.setAnimationLoop(()=>{controls.update();renderer.render(scene,camera);});
