import assert from "node:assert/strict";
import {edit,move,validate,clip,ROOT,copyCell,pasteCell,fillRegion,cellFromCoordinates} from "./dist/space.mjs";
const volume=bs=>bs.reduce((s,b)=>s+b.min.reduce((v,n,i)=>v*(b.max[i]-n),1),0);
const cube={min:[0,0,0],max:[1000,1000,1000]};
let boxes=edit([],cube,"desk","#ff5349");
const hole={min:[100,100,100],max:[200,200,200]};
boxes=edit(boxes,hole,null);
assert.equal(volume(boxes),1e9-1e6);
assert(boxes.every(b=>!clip(b,hole)));
assert.equal(volume(edit(boxes,hole,"desk","#ff5349")),1e9);
const objects=[{id:"desk",name:"Desk",kind:"movable"},{id:"wall",name:"Wall",kind:"fixed"}];
const moved=move(boxes,objects,"desk",[10,20,30]);
assert.equal(volume(moved),volume(boxes));
assert.deepEqual(moved.map(b=>b.min),boxes.map(b=>b.min.map((v,i)=>v+[10,20,30][i])));
assert.throws(()=>move(boxes,objects,"desk",[-1,0,0]),/leave/);
assert.throws(()=>move(boxes,objects,"wall",[1,0,0]),/Fixed/);
const wall={min:[1000,0,0],max:[2000,1000,1000],owner:"wall",color:"#111111"};
assert.throws(()=>move([...boxes,wall],objects,"desk",[1000,0,0]),/blocked/);
const data={version:2,unit:"mm",objects,boxes};
assert.deepEqual(validate(JSON.parse(JSON.stringify(data))),data);
assert.throws(()=>validate({...data,boxes:[...boxes,boxes[0]]}),/overlap/);
assert.throws(()=>validate({...data,boxes:[{...boxes[0],min:[-1,0,0]}]}),/Invalid/);
// Viewing and clipping never change saved geometry.
const before=JSON.stringify(data);
for(const b of boxes)clip(b,hole);
assert.equal(JSON.stringify(data),before);
assert.equal(volume([ROOT]),1e12);
// Millimeter cuts preserve every other cubic millimeter.
const tiny={min:[111,111,111],max:[112,112,112]};
assert.equal(volume(edit(edit([],cube,"desk","#ff5349"),tiny,null)),1e9-1);
console.log("Spatial tests passed: carving, exact volume, movement, collisions, boundaries, JSON and non-mutating views.");

const copied=copyCell(boxes,cube,"desk");
const destination={min:[2000,0,0],max:[3000,1000,1000]};
const repeated=pasteCell(boxes,destination,"desk",copied);
assert.equal(volume(repeated),2*volume(boxes));
assert(!repeated.some(b=>clip(b,{min:[2100,100,100],max:[2200,200,200]})));
const fullTarget=edit(boxes,destination,"desk","#111111");
assert.deepEqual(pasteCell(fullTarget,destination,"desk",copied),repeated);
assert.throws(()=>pasteCell([...boxes,{...destination,owner:"wall",color:"#111111"}],destination,"desk",copied),/blocked/);
assert.throws(()=>pasteCell(boxes,hole,"desk",copied),/scale/);
const snap=JSON.stringify(copied);
edit(repeated,destination,null);
assert.equal(JSON.stringify(copied),snap);
const slab={min:[0,0,0],max:[4000,30,3000]};
const filled=fillRegion([],slab,"wall","#111111");
assert.equal(filled.length,1);assert.equal(volume(filled),360000000);
assert.throws(()=>fillRegion(boxes,slab,"wall","#111111"),/blocked/);
assert.throws(()=>fillRegion([],{min:[9000,0,0],max:[11000,30,3000]},"wall","#111111"),/within/);
assert.throws(()=>fillRegion([],{min:[0,0,0],max:[1000,0.1,1000]},"wall","#111111"),/millimeters/);
validate({version:2,unit:"mm",objects,boxes:repeated});
console.log("Bulk tests passed: detailed copies, empty-space replacement, independent snapshots, thin fills, collisions, bounds and JSON.");

const above=cellFromCoordinates(ROOT,[2,5,7]);
assert.deepEqual(above,{min:[2000,5000,7000],max:[3000,6000,8000]});
const pastedAbove=pasteCell(boxes,above,"desk",copied);
assert.equal(volume(pastedAbove),2*volume(boxes));
assert(pastedAbove.some(b=>b.min[1]>=5000&&b.min[2]>=7000));
assert.deepEqual(cellFromCoordinates(above,[9,8,7]),{min:[2900,5800,7700],max:[3000,5900,7800]});
for(const xyz of [[0,10,0],[0,-1,0],[0,0.5,0],[0,NaN,0]])assert.throws(()=>cellFromCoordinates(ROOT,xyz),/whole numbers/);
console.log("Destination checks passed: three axes, elevated paste, nested coordinates and invalid inputs.");
